### ISSUE TITLE
`ConfigError: Couldn't resolve parser "astro"` when formatting .astro file

### ISSUE THREAD

**Issue by HereIsKevin** [sublimelsp/LSP-astro#37]
Hi,

While using Sublime Text 4143 on macOS Ventura 13.4, formatting seems to fail due `prettier-plugin-astro` being missing. 
<img width="896" alt="Screenshot 2023-06-24 at 8 20 07 PM" src="https://github.com/sublimelsp/LSP-astro/assets/49735863/9a9e48a3-6770-4f5a-a201-e6b33d4221ac">

On further inspection, it seems like `@astrojs/language-server` has `prettier-plugin-astro` as a optional peer dependency [here](https://github.com/withastro/language-tools/blob/85fa33101d635219103294e26abd464ae79422d5/packages/language-server/package.json#L72), so it is not automatically installed. This seems like it could be resolved by somehow installing `prettier-plugin-astro`, so could you look into that?

Thanks in advance!

**Comment by deathaxe** [comment]
Thank's for reporting. Prettier has been added and should be available soon.
